backend:
  replicas: 3
  image: fleetpulse-backend
  tag: stable
  port: 8000

frontend:
  replicas: 2
  image: fleetpulse-frontend
  tag: stable
  port: 80

agent:
  replicas: 2
  image: fleetpulse-agent
  tag: stable
  port: 8001

redis:
  replicas: 1
