apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetpulse-backend
  labels:
    app: fleetpulse-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: fleetpulse-backend
  template:
    metadata:
      labels:
        app: fleetpulse-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fleetpulse-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
